### ISSUE TITLE
Correcciones para deployar en producción

### ISSUE THREAD

**Issue by 3manuek** [Fundacion-Oportunidades/site#3]
- [x] La configuración de `astro.config.mjs` está apuntando a la URL de GH con el route de `site`. Deberíamos tener un comando para el build de dev y producción separados.
- [x] Varios archivos llaman utilizando `/site` en los links, esto no debería estar. Los links tienen que basarse en la baseURL (atributos defineConfig.site y base).
- [x] Agregar el build de prod y los comandos para sincronizar el S3 en el GH Actions.

**Comment by 3manuek** [comment]
@amin-farina el punto 2 ya está?

**Comment by amin-farina** [comment]
Si ya esta corregido, no se basan en un baseUrl pero si estan corregidos para funcionar en produccion
